# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LetSing' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LetSing

  pod 'SDWebImage'
  pod "Alamofire"
  pod 'YouTubePlayer', :git => 'https://github.com/boompieman/Swift-YouTube-Player.git'
  pod 'SwiftLint'
  pod 'AudioKit', '~> 4.2'
  pod 'RealmSwift'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'MJRefresh'
  pod 'Fabric'
  pod 'Crashlytics'


end
